### PR TITLE
Fixes to make work with Xcode 6.1/iOS7+

### PR DESCRIPTION
**Pull request by karmakaze**

### CODE REVIEW

**Comment by sraj** [comment]
Hey.. Any reasons why you like to change it to .jpg?

**Comment by sraj** [comment]
Thanks for request :+1: Merged it

**Comment by karmakaze** [comment]
Oh right, that. I was following the REAMDME.md at https://github.com/sraj/Swift-SRWebClient and the "Image Upload" section uses function `let imageData:NSData = NSData.dataWithData(UIImageJPEGRepresentation(image, 1.0))` which produces JPEG encoded raw bytes. So basically just consistency. Most browsers more or less ignore the image mime/extension and interpret the image data so works either way. Just seemed more appropriate.

**Comment by karmakaze** [comment]
Thanks for posting the source--there's not a lot of good working Swift example code.

**Pull request merged**
